ItemCF的实现代码，根据《推荐系统实践》这本书的思路，结合常用的数据科学计算包完成</br>
不用数据科学包的代码参考:https://github.com/Magic-Bubble/RecommendSystemPractice/blob/master/Chapter2/%E5%9F%BA%E4%BA%8E%E7%89%A9%E5%93%81%E7%9A%84%E5%8D%8F%E5%90%8C%E8%BF%87%E6%BB%A4%E7%AE%97%E6%B3%95.ipynb </br>

### 读取数据以及预处理

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
header = ['user_id', 'movie_id', 'ratings', 'timestamp']
ratings_df = pd.read_csv('ratings.dat',
                         sep='::',
                         header=None,
                         engine='python',
                         names=header,
                         usecols=[0,1,2])
#usecols 只读取前两列，本次实验用不到除了ratings.dat前两列以外的其他数据

In [3]:
ratings_df.head()

   user_id  movie_id  ratings
0        1      1193        5
1        1       661        3
2        1       914        3
3        1      3408        4
4        1      2355        5

In [4]:
# 分割，注意stratify参数必须加上，因为该数据是有序的，在1/8处直接画一条线的这种分割方式会导致无法评估算法
ratings_df_train,ratings_df_test = train_test_split(ratings_df,test_size = 0.125,stratify=ratings_df['user_id'],random_state=1)

In [5]:
# 划分后给训练集按照user_id排序(因为之前的划分过程中被打乱了)
ratings_df_train.sort_values(by='user_id', inplace=True, ascending=True)
print(ratings_df_train.shape)
ratings_df_train

(875182, 3)

         user_id  movie_id  ratings
47             1      1207        4
1              1       661        3
16             1      2687        3
21             1       720        3
19             1      2797        4
...          ...       ...      ...
1000062     6040      1251        5
1000153     6040      2384        4
1000059     6040      1249        4
999897      6040      3068        3
1000042     6040      1221        4

[875182 rows x 3 columns]

In [6]:
# 同样的，给测试集排序
ratings_df_test.sort_values(by='user_id', inplace=True, ascending=True)
print(ratings_df_test.shape)
ratings_df_test

(125027, 3)

         user_id  movie_id  ratings
12             1      2398        4
4              1      2355        5
37             1      1022        5
38             1      2762        4
51             1       608        4
...          ...       ...      ...
1000015     6040       357        3
1000066     6040      1254        5
1000008     6040      1962        3
1000079     6040      1283        4
1000011     6040      1966        4

[125027 rows x 3 columns]

In [7]:
# 查看数据集
ratings_df_train

         user_id  movie_id  ratings
47             1      1207        4
1              1       661        3
16             1      2687        3
21             1       720        3
19             1      2797        4
...          ...       ...      ...
1000062     6040      1251        5
1000153     6040      2384        4
1000059     6040      1249        4
999897      6040      3068        3
1000042     6040      1221        4

[875182 rows x 3 columns]

### 建立用户-物品索引
表示用户对物品感兴趣的列表

In [8]:
# 将数据按照'user_id'和'movie_id'进行透视，创建用户-物品矩阵，user_item_matrix作矩阵用于今后推荐
user_item_matrix = ratings_df_train.pivot(index='user_id', columns='movie_id', values='ratings').fillna(0)
user_item_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6036,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6040,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 建立物品-物品索引

In [9]:
# 计算物品相似度矩阵
item_similarity_matrix = cosine_similarity(user_item_matrix.T)
item_similarity_df = pd.DataFrame(item_similarity_matrix, index=user_item_matrix.columns, columns=user_item_matrix.columns)

In [10]:
item_similarity_df

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
movie_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.333967,0.229123,0.158550,0.214411,0.307014,0.259948,0.108810,0.093327,0.313214,...,0.088091,0.019604,0.073770,0.071607,0.043274,0.273778,0.165120,0.092458,0.039637,0.165109
2,0.333967,1.000000,0.220081,0.127614,0.220836,0.211031,0.232230,0.155940,0.139811,0.323126,...,0.057068,0.010009,0.063403,0.079209,0.069116,0.186104,0.121766,0.086395,0.024679,0.113652
3,0.229123,0.220081,1.000000,0.153549,0.270230,0.177698,0.241023,0.053688,0.130650,0.202401,...,0.035057,0.070160,0.046477,0.068716,0.045638,0.176243,0.093080,0.060080,0.011692,0.094214
4,0.158550,0.127614,0.153549,1.000000,0.246808,0.115854,0.193420,0.036302,0.054237,0.103544,...,0.038736,0.000000,0.002724,0.010741,0.015171,0.102599,0.068695,0.016254,0.014621,0.070926
5,0.214411,0.220836,0.270230,0.246808,1.000000,0.137666,0.268946,0.044853,0.120909,0.202486,...,0.024030,0.090015,0.050313,0.028571,0.006671,0.150561,0.089496,0.051883,0.005000,0.103456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3948,0.273778,0.186104,0.176243,0.102599,0.150561,0.204957,0.168364,0.069535,0.081880,0.205881,...,0.171354,0.049345,0.089572,0.166163,0.081432,1.000000,0.306179,0.153413,0.113225,0.319055
3949,0.165120,0.121766,0.093080,0.068695,0.089496,0.175904,0.087697,0.055632,0.084772,0.107782,...,0.235378,0.066513,0.072977,0.159240,0.106246,0.306179,1.000000,0.269450,0.182886,0.303797
3950,0.092458,0.086395,0.060080,0.016254,0.051883,0.090736,0.047974,0.050190,0.005381,0.089073,...,0.108589,0.202189,0.069332,0.132677,0.105951,0.153413,0.269450,1.000000,0.189300,0.185793
3951,0.039637,0.024679,0.011692,0.014621,0.005000,0.033637,0.033563,0.077594,0.000000,0.010142,...,0.175002,0.145729,0.086160,0.091664,0.017951,0.113225,0.182886,0.189300,1.000000,0.146939
3952,0.165109,0.113652,0.094214,0.070926,0.103456,0.197343,0.132810,0.019284,0.054970,0.141752,...,0.157505,0.024372,0.036947,0.151448,0.117039,0.319055,0.303797,0.185793,0.146939,1.000000

#### 使用上述表格，可以直接查找两部电影的相似度

In [11]:
# 用这种方式可以直接验证两部电影的相似度
# 这里验证的是588号电影Aladdin和364号电影Lion King
print(item_similarity_df[588][364])

# 这里验证的是588号电影Aladdin和364号电影Toy Story
print(item_similarity_df[588][1])

0.5676349086253888
0.5311441251003869

### 两个离线计算表格已经准备就绪，现在可以做推荐了

In [12]:
# 设定要推荐的用户
user_id = 1

recommend_num = 10

# 获取该用户看过的电影
watched_items = user_item_matrix.loc[user_id][user_item_matrix.loc[user_id].astype(bool)].index
print(watched_items)

Index([   1,   48,  150,  260,  527,  531,  588,  594,  595,  661,  720,  745,
        783,  914,  919,  938, 1028, 1029, 1035, 1097, 1193, 1207, 1246, 1270,
       1287, 1545, 1566, 1721, 1836, 1907, 1961, 1962, 2018, 2028, 2294, 2321,
       2340, 2687, 2692, 2791, 2797, 2918, 3105, 3114, 3186, 3408],
      dtype='int64', name='movie_id')

In [13]:
similar_movies_num_k = 80

In [14]:
# 针对每一个用户看过的电影，通过“物品 -> 物品”的索引，找到top-k相似物品
top_k_similar_items_dict = {}

for item in watched_items:
    if item in item_similarity_df.index:
        similar_items = item_similarity_df.loc[item].sort_values(ascending=False)[1:similar_movies_num_k+1]
        top_k_similar_items_dict[item] = similar_items

top_k_similar_items_dict

# 如用户看过的1号电影，根据上列物品-物品索引，可以知道最相似的电影有3144号，1265号等等

{1: movie_id
 3114    0.552638
 1265    0.537379
 588     0.531144
 2355    0.516883
 1270    0.490126
           ...
 587     0.399165
 32      0.399040
 2997    0.398909
 1259    0.398611
 1278    0.398551
 Name: 1, Length: 80, dtype: float64,
 48: movie_id
 783     0.456068
 595     0.436213
 1688    0.417552
 588     0.397226
 364     0.397119
           ...
 1569    0.246027
 2746    0.245860
 362     0.245787
 736     0.245534
 239     0.244216
 Name: 48, Length: 80, dtype: float64,
 150: movie_id
 1704    0.505320
 2268    0.474058
 1682    0.472194
 318     0.463508
 1393    0.459842
           ...
 260     0.358043
 1968    0.357504
 3253    0.356996
 1962    0.355560
 2890    0.355404
 Name: 150, Length: 80, dtype: float64,
 260: movie_id
 1196    0.693559
 1210    0.645882
 1198    0.630641
 1240    0.598796
 1214    0.598042
           ...
 316     0.432070
 3175    0.431373
 2918    0.431191
 1573    0.430809
 3703    0.430434
 Name: 260, Length: 80, dtype: float64,
 527: movie_id
 318     0.559590
 593     0.542939
 2028    0.541525
 608     0.524958
 296     0.505857
           ...
 1584    0.378873
 1968    0.378429
 1394    0.378410
 1222    0.378244
 1961    0.378210
 Name: 527, Length: 80, dtype: float64,
 531: movie_id
 262     0.316783
 261     0.276448
 595     0.268233
 2059    0.267975
 1271    0.264295
           ...
 1183    0.207880
 551     0.207743
 2739    0.207728
 2355    0.207232
 500     0.207227
 Name: 531, Length: 80, dtype: float64,
 588: movie_id
 595     0.576250
 364     0.567635
 1       0.531144
 2081    0.528927
 2355    0.460615
           ...
 1968    0.364837
 589     0.364237
 2746    0.363565
 2054    0.363480
 2302    0.363451
 Name: 588, Length: 80, dtype: float64,
 594: movie_id
 1022    0.600520
 2096    0.576956
 1029    0.573458
 596     0.560661
 2087    0.559041
           ...
 2716    0.314674
 1265    0.314210
 3471    0.314196
 2005    0.313739
 910     0.313507
 Name: 594, Length: 80, dtype: float64,
 595: movie_id
 364     0.587740
 588     0.576250
 2081    0.524928
 1022    0.516852
 594     0.504816
           ...
 2628    0.339212
 780     0.338822
 3489    0.338076
 2090    0.337794
 914     0.337509
 Name: 595, Length: 80, dtype: float64,
 661: movie_id
 551     0.402109
 595     0.377339
 364     0.375946
 783     0.352690
 1022    0.350319
           ...
 1356    0.252175
 2105    0.251959
 1033    0.251538
 541     0.250824
 2968    0.250345
 Name: 661, Length: 80, dtype: float64,
 720: movie_id
 1148    0.439624
 1223    0.418385
 745     0.405979
 1       0.291290
 3429    0.287738
           ...
 1210    0.218234
 1249    0.218010
 1097    0.217359
 2858    0.217179
 3108    0.215465
 Name: 720, Length: 80, dtype: float64,
 745: movie_id
 1148    0.654625
 1223    0.598399
 3429    0.437723
 720     0.405979
 3751    0.360640
           ...
 2916    0.234721
 1200    0.234606
 589     0.234292
 1291    0.234011
 2762    0.233312
 Name: 745, Length: 80, dtype: float64,
 783: movie_id
 1566    0.487299
 595     0.477991
 48      0.456068
 1907    0.447845
 588     0.423111
           ...
 2987    0.254770
 2640    0.254677
 1580    0.253102
 1031    0.252601
 317     0.252535
 Name: 783, Length: 80, dtype: float64,
 914: movie_id
 1947    0.527681
 2565    0.472388
 899     0.464462
 1035    0.452335
 1028    0.426069
           ...
 3072    0.285169
 1294    0.284390
 1270    0.284371
 3451    0.284264
 2243    0.283274
 Name: 914, Length: 80, dtype: float64,
 919: movie_id
 1196    0.496174
 260     0.490656
 912     0.486448
 1097    0.485986
 1198    0.480599
           ...
 2396    0.390631
 2918    0.390414
 2406    0.389346
 910     0.388551
 1380    0.388356
 Name: 919, Length: 80, dtype: float64,
 938: movie_id
 2565    0.433228
 3549    0.410705
 900     0.405723
 914     0.383918
 2941    0.375866
           ...
 943     0.206078
 2081    0.205768
 3251    0.205135
 3599    0.205057
 1944    0.204691
 Name: 938, Length: 80, dtype: float64,
 1028: movie_id
 2078    0.494752
 1022    0.487651
 594     0.481157
 2081    0.480069
 2080    0.479087
           ...
 2857    0.334697
 1259    0.334648
 2321    0.334444
 1013    0.334249
 1951    0.334223
 Name: 1028, Length: 80, dtype: float64,
 1029: movie_id
 1022    0.577763
 594     0.573458
 2096    0.558988
 596     0.544203
 2087    0.539265
           ...
 900     0.294485
 1270    0.294436
 2657    0.294156
 2140    0.293338
 1197    0.292839
 Name: 1029, Length: 80, dtype: float64,
 1035: movie_id
 1028    0.477997
 1947    0.476543
 914     0.452335
 2565    0.430747
 594     0.421020
           ...
 903     0.296571
 110     0.295510
 1079    0.295347
 2020    0.295334
 2529    0.295261
 Name: 1035, Length: 80, dtype: float64,
 1097: movie_id
 1196    0.577108
 260     0.563489
 1270    0.556249
 1210    0.533218
 1240    0.529343
           ...
 2455    0.414827
 1136    0.414685
 1079    0.412610
 110     0.412385
 1356    0.411126
 Name: 1097, Length: 80, dtype: float64,
 1193: movie_id
 858     0.471569
 1208    0.461058
 111     0.460817
 1225    0.458524
 608     0.458407
           ...
 1674    0.354606
 1197    0.354110
 920     0.352117
 2762    0.352098
 1210    0.351076
 Name: 1193, Length: 80, dtype: float64,
 1207: movie_id
 1247    0.458723
 923     0.438603
 1193    0.433915
 1225    0.431534
 1952    0.424508
           ...
 1674    0.321983
 1394    0.321013
 922     0.320309
 2300    0.320164
 1265    0.319954
 Name: 1207, Length: 80, dtype: float64,
 1246: movie_id
 1302    0.478244
 1961    0.474798
 1968    0.470005
 2420    0.457266
 1962    0.438570
           ...
 454     0.350714
 2987    0.350565
 1293    0.349542
 1220    0.348452
 3071    0.347058
 Name: 1246, Length: 80, dtype: float64,
 1270: movie_id
 1196    0.600330
 260     0.584172
 1210    0.570619
 1097    0.556249
 1240    0.553210
           ...
 1356    0.434259
 2915    0.434004
 527     0.433887
 3039    0.432427
 858     0.431472
 Name: 1270, Length: 80, dtype: float64,
 1287: movie_id
 2947    0.408202
 1953    0.396266
 2944    0.396004
 2366    0.392551
 1198    0.388707
           ...
 1019    0.311319
 2872    0.310856
 1253    0.310698
 1084    0.309921
 480     0.309036
 Name: 1287, Length: 80, dtype: float64,
 1545: movie_id
 2610    0.240387
 331     0.207638
 1187    0.190995
 1280    0.183969
 1041    0.183624
           ...
 1116    0.139060
 57      0.138865
 290     0.138854
 2611    0.138754
 3720    0.138664
 Name: 1545, Length: 80, dtype: float64,
 1566: movie_id
 783     0.487299
 1907    0.478408
 2687    0.443056
 595     0.440937
 364     0.426089
           ...
 1097    0.256497
 2640    0.254375
 2193    0.254349
 362     0.253853
 1702    0.252806
 Name: 1566, Length: 80, dtype: float64,
 1721: movie_id
 1393    0.454620
 356     0.435938
 587     0.429388
 1704    0.425991
 150     0.424659
           ...
 1246    0.335438
 2918    0.335214
 3386    0.334654
 34      0.334407
 1617    0.334141
 Name: 1721, Length: 80, dtype: float64,
 1836: movie_id
 1701    0.272926
 125     0.267854
 538     0.264841
 1635    0.262622
 372     0.251676
           ...
 16      0.191004
 1916    0.190873
 3261    0.190536
 2611    0.190374
 2599    0.190153
 Name: 1836, Length: 80, dtype: float64,
 1907: movie_id
 2687    0.501419
 1566    0.478408
 595     0.460906
 364     0.451167
 783     0.447845
           ...
 1588    0.257107
 1198    0.256882
 3000    0.255356
 367     0.254430
 2142    0.254411
 Name: 1907, Length: 80, dtype: float64,
 1961: movie_id
 1246    0.474798
 1302    0.448151
 1962    0.428642
 1097    0.427393
 2918    0.421160
           ...
 587     0.352283
 1957    0.351747
 3591    0.350739
 110     0.350504
 2396    0.349724
 Name: 1961, Length: 80, dtype: float64,
 1962: movie_id
 1302    0.464084
 2739    0.462297
 1246    0.438570
 1961    0.428642
 1674    0.406499
           ...
 1103    0.316818
 1193    0.316482
 1393    0.315547
 3363    0.315087
 508     0.314337
 Name: 1962, Length: 80, dtype: float64,
 2018: movie_id
 596     0.547723
 594     0.538168
 1029    0.518972
 1022    0.506854
 2085    0.492988
           ...
 899     0.285821
 1197    0.285110
 2407    0.283340
 2011    0.283157
 2005    0.282279
 Name: 2018, Length: 80, dtype: float64,
 2028: movie_id
 110     0.564384
 457     0.551281
 593     0.541606
 527     0.541525
 1196    0.541104
           ...
 1193    0.401421
 1721    0.401367
 349     0.400670
 2427    0.399687
 1784    0.399101
 Name: 2028, Length: 80, dtype: float64,
 2294: movie_id
 364     0.460870
 1907    0.440959
 595     0.422914
 588     0.414830
 1       0.395425
           ...
 2394    0.303537
 2005    0.303009
 380     0.301750
 316     0.301492
 153     0.301258
 Name: 2294, Length: 80, dtype: float64,
 2321: movie_id
 1265    0.485326
 1641    0.463810
 1923    0.462000
 1784    0.457913
 39      0.450350
           ...
 150     0.361992
 1614    0.361441
 2291    0.361324
 1136    0.360763
 2762    0.360448
 Name: 2321, Length: 80, dtype: float64,
 2340: movie_id
 802     0.311702
 587     0.308861
 539     0.306187
 3259    0.299746
 2424    0.299512
           ...
 647     0.225323
 590     0.224522
 252     0.224424
 1625    0.224355
 2942    0.224299
 Name: 2340, Length: 80, dtype: float64,
 2687: movie_id
 1907    0.501419
 1566    0.443056
 364     0.414540
 595     0.409240
 783     0.392430
           ...
 1073    0.234108
 457     0.233340
 2321    0.232402
 2006    0.232140
 2797    0.231803
 Name: 2687, Length: 80, dtype: float64,
 2692: movie_id
 50      0.411053
 2858    0.399498
 2599    0.395081
 2997    0.393236
 296     0.392771
           ...
 377     0.302687
 3317    0.301050
 110     0.300615
 1210    0.299905
 1270    0.299883
 Name: 2692, Length: 80, dtype: float64,
 2791: movie_id
 2918    0.509983
 1270    0.508125
 2716    0.501057
 1259    0.497678
 1079    0.493448
           ...
 2028    0.384845
 3526    0.381806
 2407    0.381345
 1784    0.381195
 2571    0.380635
 Name: 2791, Length: 80, dtype: float64,
 2797: movie_id
 2174    0.598322
 2100    0.560059
 2918    0.539171
 1270    0.533539
 2716    0.519829
           ...
 3396    0.401926
 2161    0.400922
 380     0.400856
 1610    0.400474
 2001    0.400157
 Name: 2797, Length: 80, dtype: float64,
 2918: movie_id
 1968    0.559093
 1079    0.553774
 1270    0.552940
 2797    0.539171
 1307    0.537797
           ...
 2858    0.409210
 1580    0.408514
 593     0.407254
 1784    0.406656
 1278    0.405542
 Name: 2918, Length: 80, dtype: float64,
 3105: movie_id
 150     0.426986
 1704    0.422689
 337     0.397454
 1682    0.387810
 300     0.385993
           ...
 953     0.300533
 1270    0.299322
 515     0.298589
 588     0.297880
 50      0.296931
 Name: 3105, Length: 80, dtype: float64,
 3114: movie_id
 1       0.552638
 2355    0.494424
 1265    0.422618
 2396    0.411991
 34      0.408711
           ...
 2683    0.319121
 2804    0.319108
 1584    0.318876
 367     0.318034
 1356    0.317473
 Name: 3114, Length: 80, dtype: float64,
 3186: movie_id
 3147    0.311676
 2858    0.278468
 3176    0.277803
 3148    0.273259
 2908    0.258378
           ...
 3252    0.201067
 1407    0.201028
 337     0.200634
 587     0.200464
 2571    0.200383
 Name: 3186, Length: 80, dtype: float64,
 3408: movie_id
 3578    0.405218
 2762    0.401761
 2858    0.394068
 3176    0.384853
 2396    0.378386
           ...
 2770    0.286175
 2712    0.285900
 2291    0.285608
 36      0.285183
 1584    0.285075
 Name: 3408, Length: 80, dtype: float64}

In [15]:
movie_scores = {}

# 计算每个相似电影的总相似度，这里只是单纯简单地相加，实际上这样的做法需要改进，结合课件ItemCF的内容，说说你的看法
for movie, similar_items in top_k_similar_items_dict.items():
    for similar_movie, similarity_score in similar_items.items():
        if similar_movie not in movie_scores:
            movie_scores[similar_movie] = 0
        movie_scores[similar_movie] = movie_scores[similar_movie] + similarity_score * user_item_matrix.loc[user_id,movie]

# 对推荐电影按照总相似度进行排序
recommendations = sorted(movie_scores.items(), key=lambda x: x[1], reverse=True)
recommendations

[(1196, np.float64(58.14925595676199)),
 (1097, np.float64(56.2650093573387)),
 (1270, np.float64(54.15909071983632)),
 (1, np.float64(53.52689316073251)),
 (1265, np.float64(52.497596689914644)),
 (1198, np.float64(51.414838494877394)),
 (260, np.float64(48.72120733538936)),
 (1210, np.float64(47.33033760597222)),
 (2797, np.float64(44.897388021205494)),
 (2987, np.float64(43.137615048983285)),
 (919, np.float64(42.02910204095146)),
 (1197, np.float64(41.044886550557585)),
 (592, np.float64(40.618734013460866)),
 (593, np.float64(40.33598515544499)),
 (318, np.float64(39.827341958323856)),
 (2716, np.float64(39.6878425642731)),
 (588, np.float64(38.31121610391188)),
 (356, np.float64(38.28290409649106)),
 (296, np.float64(38.14295004076712)),
 (364, np.float64(37.82143164468238)),
 (1580, np.float64(37.78016136659865)),
 (2081, np.float64(37.6946233462043)),
 (2174, np.float64(37.36975287346132)),
 (1073, np.float64(36.98072733139939)),
 (608, np.float64(36.88914415021277)),
 (595, np.float64(34.283610653491536)),
 (1259, np.float64(34.23940992579588)),
 (1307, np.float64(34.21514255734086)),
 (2571, np.float64(33.85356364303985)),
 (1291, np.float64(33.56873042877438)),
 (2858, np.float64(33.35951939052473)),
 (480, np.float64(33.33811232348077)),
 (2918, np.float64(32.84142504571201)),
 (457, np.float64(32.37111630279746)),
 (527, np.float64(32.364855593697825)),
 (1022, np.float64(31.004064227429506)),
 (2028, np.float64(30.462428261607787)),
 (2396, np.float64(30.217457553287872)),
 (1136, np.float64(29.667385367152583)),
 (1968, np.float64(29.614220955986323)),
 (1282, np.float64(29.1140779064778)),
 (594, np.float64(28.952533563303973)),
 (1240, np.float64(28.320006860141465)),
 (2080, np.float64(28.22923914356061)),
 (2096, np.float64(28.071138576631743)),
 (2355, np.float64(27.837542307818424)),
 (1704, np.float64(27.682814683680533)),
 (2078, np.float64(27.474999706567274)),
 (1036, np.float64(27.4371041478716)),
 (2087, np.float64(27.268202879485962)),
 (590, np.float64(27.034578609830646)),
 (2762, np.float64(26.864832688170058)),
 (110, np.float64(26.817773829315577)),
 (1617, np.float64(26.259234958900826)),
 (1394, np.float64(26.14275639355331)),
 (2100, np.float64(25.99227259871263)),
 (1079, np.float64(25.9133682620533)),
 (589, np.float64(25.524685020243936)),
 (1032, np.float64(25.452176875763644)),
 (2640, np.float64(24.672448271929344)),
 (1029, np.float64(24.642288666145628)),
 (2406, np.float64(24.348697097906992)),
 (1028, np.float64(24.26869723355137)),
 (1784, np.float64(24.14033770126862)),
 (2000, np.float64(24.109785246447682)),
 (1393, np.float64(23.862644176919524)),
 (2054, np.float64(23.629933901390572)),
 (3471, np.float64(23.41862658524074)),
 (3448, np.float64(23.401900235388396)),
 (50, np.float64(23.260593313756406)),
 (858, np.float64(22.887756708999373)),
 (2018, np.float64(22.666917896282705)),
 (2291, np.float64(22.273915221427373)),
 (150, np.float64(22.209132358926993)),
 (1225, np.float64(22.199400317274304)),
 (1387, np.float64(21.895124664026035)),
 (2085, np.float64(21.702268802952275)),
 (377, np.float64(21.360241367637194)),
 (34, np.float64(21.28751343610604)),
 (1214, np.float64(20.788248589309777)),
 (2628, np.float64(20.667734854924262)),
 (1584, np.float64(20.64744632798155)),
 (2916, np.float64(20.56455158844314)),
 (953, np.float64(20.425960800348346)),
 (596, np.float64(20.297555577390764)),
 (1200, np.float64(19.84149106942617)),
 (783, np.float64(19.454829317852667)),
 (2791, np.float64(19.439458063195364)),
 (1907, np.float64(19.425494811541768)),
 (2294, np.float64(18.96923003955048)),
 (3396, np.float64(18.84214944668698)),
 (2137, np.float64(18.758808176324955)),
 (780, np.float64(18.743799746215842)),
 (1610, np.float64(18.61845846506236)),
 (3253, np.float64(18.525143469756504)),
 (2268, np.float64(18.361900421060643)),
 (1025, np.float64(18.12147004052432)),
 (3114, np.float64(17.751041601915432)),
 (39, np.float64(17.626306124088323)),
 (1566, np.float64(17.545068617850337)),
 (1961, np.float64(17.479671506476972)),
 (551, np.float64(17.478432088272907)),
 (3034, np.float64(17.44995732663994)),
 (48, np.float64(17.319418898575)),
 (1682, np.float64(17.290515702043667)),
 (2011, np.float64(17.242459950204534)),
 (1688, np.float64(17.09270862683932)),
 (541, np.float64(16.967911173601383)),
 (1947, np.float64(16.914851464226455)),
 (32, np.float64(16.796549902685797)),
 (1035, np.float64(16.693019836284105)),
 (2407, np.float64(16.665953473587752)),
 (587, np.float64(16.48004421629626)),
 (2161, np.float64(16.437764038584525)),
 (924, np.float64(16.254336705447923)),
 (2089, np.float64(16.226885537892688)),
 (1380, np.float64(16.207348799532884)),
 (2687, np.float64(16.118371406433738)),
 (1220, np.float64(16.118337661434882)),
 (2321, np.float64(16.083907985005432)),
 (2997, np.float64(16.00708693737582)),
 (3418, np.float64(15.592418926156645)),
 (1030, np.float64(15.494833967220991)),
 (2804, np.float64(15.471794595888579)),
 (1246, np.float64(15.437961455308608)),
 (661, np.float64(15.435429924400356)),
 (1033, np.float64(15.105215408080571)),
 (616, np.float64(15.009796862603972)),
 (1923, np.float64(14.99648673037067)),
 (2470, np.float64(14.923861556132149)),
 (2141, np.float64(14.514427367256191)),
 (912, np.float64(14.475213310672144)),
 (2090, np.float64(14.442296988604198)),
 (1221, np.float64(14.304618377666285)),
 (380, np.float64(14.287390545767352)),
 (1674, np.float64(14.119124252870293)),
 (899, np.float64(13.923777795381117)),
 (2194, np.float64(13.721296607378516)),
 (914, np.float64(13.606389586500242)),
 (1278, np.float64(13.404650674060766)),
 (1213, np.float64(13.343435304018683)),
 (1517, np.float64(13.302191592873694)),
 (3255, np.float64(13.25825813282328)),
 (1247, np.float64(13.188453207717558)),
 (3361, np.float64(12.83409821534131)),
 (920, np.float64(12.788047287937033)),
 (1090, np.float64(12.757429741518683)),
 (3363, np.float64(12.68726907700513)),
 (1721, np.float64(12.663235244875686)),
 (3526, np.float64(12.599914260938045)),
 (2915, np.float64(12.538083410531618)),
 (3039, np.float64(12.490075048372463)),
 (1193, np.float64(12.260978843149825)),
 (3147, np.float64(12.240407900367883)),
 (1954, np.float64(12.214619152827108)),
 (2746, np.float64(12.077158693260959)),
 (1294, np.float64(11.98624167823271)),
 (1302, np.float64(11.868315546687526)),
 (2139, np.float64(11.775186217867901)),
 (2565, np.float64(11.75480861065866)),
 (367, np.float64(11.720569354735499)),
 (508, np.float64(11.441557015331263)),
 (1088, np.float64(11.438270233877326)),
 (2115, np.float64(11.37678211310676)),
 (750, np.float64(11.29775787829264)),
 (1208, np.float64(11.222713138509178)),
 (3421, np.float64(10.934921870695897)),
 (3671, np.float64(10.87751726810024)),
 (1358, np.float64(10.703166123830947)),
 (357, np.float64(10.517949211653605)),
 (2394, np.float64(10.231318641406604)),
 (1304, np.float64(10.19880373156389)),
 (709, np.float64(10.198117143799614)),
 (2005, np.float64(9.896154391573598)),
 (1962, np.float64(9.725026436603867)),
 (2352, np.float64(9.638595474489568)),
 (2761, np.float64(9.562829007320286)),
 (1641, np.float64(9.552019067005705)),
 (1219, np.float64(9.509218584587636)),
 (3489, np.float64(9.352840381958536)),
 (1222, np.float64(9.266475987025096)),
 (597, np.float64(9.180354440094762)),
 (2857, np.float64(9.145117202777973)),
 (2012, np.float64(9.069944446938536)),
 (3210, np.float64(9.023993474707266)),
 (539, np.float64(8.786549336609552)),
 (1206, np.float64(8.785645641265711)),
 (1500, np.float64(8.715826864185395)),
 (3105, np.float64(8.60347404119849)),
 (36, np.float64(8.55795954211361)),
 (1271, np.float64(8.514003099493824)),
 (11, np.float64(8.472959282942611)),
 (1242, np.float64(8.440386961161149)),
 (1094, np.float64(8.414220273703048)),
 (904, np.float64(8.325330786966154)),
 (1231, np.float64(8.19397896200115)),
 (440, np.float64(8.112095856225814)),
 (1374, np.float64(8.11005130891401)),
 (2123, np.float64(8.09087336345497)),
 (586, np.float64(8.07759841932354)),
 (1031, np.float64(8.005329901920696)),
 (2144, np.float64(7.988632764892349)),
 (2599, np.float64(7.980141617353448)),
 (2, np.float64(7.920007547122817)),
 (903, np.float64(7.899496466308019)),
 (908, np.float64(7.8441586413615365)),
 (2890, np.float64(7.789074057821588)),
 (1356, np.float64(7.751286368247575)),
 (910, np.float64(7.721718490817631)),
 (3527, np.float64(7.721007716783557)),
 (2739, np.float64(7.655310614555155)),
 (62, np.float64(7.5242806086840375)),
 (1234, np.float64(7.521967982783026)),
 (3751, np.float64(7.507659174381204)),
 (3552, np.float64(7.502528051340928)),
 (3578, np.float64(7.438003891542227)),
 (1013, np.float64(7.436459536701612)),
 (900, np.float64(7.370651065802257)),
 (300, np.float64(7.357832456218698)),
 (1089, np.float64(7.329242610154589)),
 (1951, np.float64(7.320458271728031)),
 (1127, np.float64(7.291026688656567)),
 (2092, np.float64(7.284161743938269)),
 (25, np.float64(7.251891161670367)),
 (1673, np.float64(7.202341549560632)),
 (2302, np.float64(7.156839112956432)),
 (923, np.float64(7.059753772524831)),
 (2529, np.float64(7.0054319453325125)),
 (2657, np.float64(6.962461041204875)),
 (1250, np.float64(6.898911819345539)),
 (1663, np.float64(6.895772924169366)),
 (2324, np.float64(6.7827382801546)),
 (1285, np.float64(6.778144566295451)),
 (3100, np.float64(6.69109199904883)),
 (1527, np.float64(6.4383309289312365)),
 (337, np.float64(6.24071678215876)),
 (3175, np.float64(6.189116812087712)),
 (454, np.float64(6.151863737322828)),
 (1207, np.float64(6.112347191230152)),
 (2420, np.float64(6.0571322501060925)),
 (1023, np.float64(6.024467095013994)),
 (1376, np.float64(6.0024338693994554)),
 (2985, np.float64(5.999147543368988)),
 (1377, np.float64(5.750275265995701)),
 (1064, np.float64(5.7132426717287395)),
 (2968, np.float64(5.706820502237619)),
 (2395, np.float64(5.7026827696714575)),
 (500, np.float64(5.6908307189888765)),
 (673, np.float64(5.690406815018439)),
 (2048, np.float64(5.590335975488424)),
 (969, np.float64(5.513457677906267)),
 (317, np.float64(5.460171460237577)),
 (1588, np.float64(5.448430567339032)),
 (2099, np.float64(5.408727051548135)),
 (1573, np.float64(5.105623775741659)),
 (111, np.float64(5.079662587148382)),
 (3545, np.float64(5.067449585602741)),
 (3098, np.float64(5.0596083343827525)),
 (3360, np.float64(5.057678110158044)),
 (3608, np.float64(5.0545745959110135)),
 (1276, np.float64(5.035303686115277)),
 (1080, np.float64(5.020065134397413)),
 (3386, np.float64(4.967651104106901)),
 (1084, np.float64(4.958347052607053)),
 (3591, np.float64(4.907039837638959)),
 (1230, np.float64(4.864307141142412)),
 (1288, np.float64(4.831047025997231)),
 (2083, np.float64(4.823186198263437)),
 (1957, np.float64(4.814793799959553)),
 (2371, np.float64(4.764753535151906)),
 (1747, np.float64(4.7421825895408425)),
 (2424, np.float64(4.688771244977001)),
 (2671, np.float64(4.6515219625280535)),
 (648, np.float64(4.595580925502878)),
 (1569, np.float64(4.585813668221495)),
 (1148, np.float64(4.572141056601774)),
 (3252, np.float64(4.374385793330779)),
 (158, np.float64(4.365659810729095)),
 (529, np.float64(4.364506334183325)),
 (362, np.float64(4.335606188986721)),
 (2105, np.float64(4.323856887950497)),
 (2142, np.float64(4.305462739953759)),
 (1293, np.float64(4.27662743056969)),
 (2059, np.float64(4.260651304363828)),
 (736, np.float64(4.254874644318761)),
 (3481, np.float64(4.247437632016193)),
 (1777, np.float64(4.2469219071012345)),
 (3108, np.float64(4.239230906791917)),
 (3675, np.float64(4.235200703198943)),
 (1186, np.float64(4.14750091582669)),
 (2700, np.float64(4.141975864929343)),
 (3549, np.float64(4.126102118576344)),
 (2140, np.float64(4.019367539149524)),
 (2908, np.float64(4.01003627540398)),
 (778, np.float64(4.004930058783605)),
 (3176, np.float64(3.943923903368511)),
 (3398, np.float64(3.9383944200302814)),
 (2020, np.float64(3.903084939395229)),
 (2124, np.float64(3.896935342431461)),
 (1012, np.float64(3.885897433177413)),
 (1639, np.float64(3.800652509306357)),
 (3793, np.float64(3.7780373508624034)),
 (1952, np.float64(3.730986468202709)),
 (1268, np.float64(3.7115947302936974)),
 (1081, np.float64(3.7038546682079705)),
 (2959, np.float64(3.672712365885931)),
 (1120, np.float64(3.670823230559705)),
 (2067, np.float64(3.667194740359207)),
 (1258, np.float64(3.6120371561599436)),
 (239, np.float64(3.5536444261196474)),
 (2871, np.float64(3.511774478081236)),
 (153, np.float64(3.4940157472391817)),
 (2193, np.float64(3.488455062290618)),
 (1252, np.float64(3.4561138184125095)),
 (3702, np.float64(3.436797339200268)),
 (1702, np.float64(3.390733964536909)),
 (1370, np.float64(3.3358969613494205)),
 (1228, np.float64(3.3258654458242103)),
 (3087, np.float64(3.3203339893732577)),
 (2003, np.float64(3.2854830953775176)),
 (2366, np.float64(3.2769451941893366)),
 (21, np.float64(3.275893642816736)),
 (2354, np.float64(3.265393116872969)),
 (1920, np.float64(3.255726612714673)),
 (2001, np.float64(3.251390490744406)),
 (1204, np.float64(3.2370227236476325)),
 (3504, np.float64(3.2350984442803203)),
 (1183, np.float64(3.1819418177930543)),
 (1678, np.float64(3.1612351473277425)),
 (2082, np.float64(3.135549262097662)),
 (1124, np.float64(3.117182386889551)),
 (2728, np.float64(3.109785604900563)),
 (2398, np.float64(3.0945210900680467)),
 (1021, np.float64(3.0740497946093566)),
 (1223, np.float64(3.050351902588833)),
 (1024, np.float64(2.9426879645436137)),
 (316, np.float64(2.934248516354411)),
 (1017, np.float64(2.85554041940906)),
 (832, np.float64(2.8457620587189583)),
 (2145, np.float64(2.8279674038750144)),
 (2474, np.float64(2.803272132964941)),
 (3071, np.float64(2.7875927609118336)),
 (47, np.float64(2.7764019421951853)),
 (938, np.float64(2.751673176532665)),
 (3897, np.float64(2.6564851968930645)),
 (3160, np.float64(2.627863195515464)),
 (1103, np.float64(2.627740125319506)),
 (235, np.float64(2.6094933730241734)),
 (2941, np.float64(2.590688011869964)),
 (3148, np.float64(2.59034147949711)),
 (223, np.float64(2.5881584156340804)),
 (1266, np.float64(2.551398448780946)),
 (515, np.float64(2.5256950117359955)),
 (2683, np.float64(2.521394084676974)),
 (3317, np.float64(2.5014645648997567)),
 (901, np.float64(2.4820991199713687)),
 (2863, np.float64(2.425117058742728)),
 (2712, np.float64(2.358539842797998)),
 (2243, np.float64(2.2938173607717234)),
 (1416, np.float64(2.2932999669718486)),
 (902, np.float64(2.2733149927540115)),
 (1060, np.float64(2.246402168996273)),
 (3061, np.float64(2.238072963842699)),
 (3072, np.float64(2.208259739416059)),
 (455, np.float64(2.1911941955472005)),
 (339, np.float64(2.1857666215271685)),
 (733, np.float64(2.18114251973025)),
 (3429, np.float64(2.176382687753631)),
 (2971, np.float64(2.168013539090131)),
 (2336, np.float64(2.1586253948278875)),
 (107, np.float64(2.1393490727796713)),
 (3052, np.float64(2.1370790428922604)),
 (372, np.float64(2.1245139981736454)),
 (3256, np.float64(2.1037475264924597)),
 (474, np.float64(2.0911626495421896)),
 (945, np.float64(2.0881083079379055)),
 (441, np.float64(2.0823514878582254)),
 (313, np.float64(2.0679736906261654)),
 (3301, np.float64(2.051015173434313)),
 (2353, np.float64(2.043546504194618)),
 (2947, np.float64(2.041010256609431)),
 (2724, np.float64(2.0351363360315493)),
 (1263, np.float64(2.030020318549891)),
 (6, np.float64(2.0195931466492936)),
 (349, np.float64(2.003348044113526)),
 (2427, np.float64(1.9984332849509556)),
 (17, np.float64(1.9939208118845921)),
 (1635, np.float64(1.9878035105904353)),
 (1953, np.float64(1.9813275076357768)),
 (2944, np.float64(1.980021744254369)),
 (3362, np.float64(1.9792594058903838)),
 (916, np.float64(1.9739361616515083)),
 (915, np.float64(1.940137827726201)),
 (2108, np.float64(1.9382169906008124)),
 (1262, np.float64(1.938063293519131)),
 (45, np.float64(1.920465403147856)),
 (161, np.float64(1.9157492870100425)),
 (911, np.float64(1.9083659017301624)),
 (1614, np.float64(1.904816832008056)),
 (1967, np.float64(1.8982547012637712)),
 (898, np.float64(1.8846074930007761)),
 (2912, np.float64(1.8749697230162972)),
 (2949, np.float64(1.8709166590329613)),
 (1729, np.float64(1.8628518039487734)),
 (2501, np.float64(1.8312644362550814)),
 (2289, np.float64(1.826686794163911)),
 (940, np.float64(1.8236848063499989)),
 (1608, np.float64(1.813964306472343)),
 (1201, np.float64(1.8084945495025309)),
 (2948, np.float64(1.8083400928986537)),
 (1272, np.float64(1.8031953272037433)),
 (928, np.float64(1.7879821224018375)),
 (933, np.float64(1.7791628144584712)),
 (3668, np.float64(1.7776970369654292)),
 (2248, np.float64(1.770299278959491)),
 (16, np.float64(1.7684920000515114)),
 (1283, np.float64(1.7682523821728315)),
 (2792, np.float64(1.7673020299530469)),
 (3654, np.float64(1.7464916033738385)),
 (2590, np.float64(1.744392584235173)),
 (1257, np.float64(1.7301637030837045)),
 (2006, np.float64(1.723931989287165)),
 (3703, np.float64(1.7217348470918747)),
 (3244, np.float64(1.7130245516994471)),
 (3451, np.float64(1.7081175332270677)),
 (1365, np.float64(1.7053713054123096)),
 (1041, np.float64(1.7018400683958779)),
 (2991, np.float64(1.6980301458443878)),
 (3868, np.float64(1.6843232232468175)),
 (2019, np.float64(1.6802390098405922)),
 (2795, np.float64(1.662792137972772)),
 (2455, np.float64(1.6593081417483437)),
 (2134, np.float64(1.6528091412537778)),
 (1297, np.float64(1.646770529805345)),
 (501, np.float64(1.6465151461330985)),
 (2951, np.float64(1.6461293272081283)),
 (2160, np.float64(1.6421952102357384)),
 (2125, np.float64(1.6403602493713563)),
 (3260, np.float64(1.6324457572443742)),
 (3168, np.float64(1.6148375521993774)),
 (3035, np.float64(1.6095508173873365)),
 (2150, np.float64(1.6086377508940002)),
 (253, np.float64(1.6007683631261513)),
 (3062, np.float64(1.581679572038642)),
 (2993, np.float64(1.580422274882839)),
 (1233, np.float64(1.5702636874670528)),
 (1275, np.float64(1.565529418503437)),
 (1254, np.float64(1.5644277890686784)),
 (1019, np.float64(1.556593227681913)),
 (2872, np.float64(1.5542795868409685)),
 (1253, np.float64(1.5534875690528551)),
 (148, np.float64(1.5471170690777336)),
 (1199, np.float64(1.5449627582581993)),
 (1810, np.float64(1.5423973880955757)),
 (369, np.float64(1.541223320280677)),
 (2088, np.float64(1.5369032446333066)),
 (1958, np.float64(1.5312521093609386)),
 (1061, np.float64(1.5215252890174997)),
 (3107, np.float64(1.5193517072395026)),
 (57, np.float64(1.5193125323851446)),
 (1096, np.float64(1.5185149899476842)),
 (3499, np.float64(1.5177313659242246)),
 (1357, np.float64(1.512151883217886)),
 (2611, np.float64(1.5068843710887316)),
 (3623, np.float64(1.5060876390225064)),
 (1274, np.float64(1.506065658392809)),
 (1625, np.float64(1.5031298597858394)),
 (2312, np.float64(1.495354180680176)),
 (2692, np.float64(1.495262056332949)),
 (1950, np.float64(1.4838606107212005)),
 (1956, np.float64(1.4790780342749046)),
 (2313, np.float64(1.478618418795537)),
 (3095, np.float64(1.4749310003449072)),
 (3468, np.float64(1.4725914125785284)),
 (1185, np.float64(1.4717090002590472)),
 (1945, np.float64(1.4675391904017843)),
 (1104, np.float64(1.4614780319225122)),
 (2580, np.float64(1.4572315296714258)),
 (1955, np.float64(1.4539335520183794)),
 (1912, np.float64(1.438602987039718)),
 (1203, np.float64(1.4305395135033017)),
 (1267, np.float64(1.4123736018743336)),
 (3753, np.float64(1.4070880049148284)),
 (1101, np.float64(1.4065603758247889)),
 (954, np.float64(1.3873423987388693)),
 (2245, np.float64(1.3767313549966909)),
 (3510, np.float64(1.368189624109278)),
 (1701, np.float64(1.364630075811635)),
 (918, np.float64(1.3610955540109888)),
 (125, np.float64(1.3392698382621473)),
 (3359, np.float64(1.3387428216877897)),
 (3298, np.float64(1.338569311895993)),
 (3684, np.float64(1.3333136937696004)),
 (2429, np.float64(1.3243372938430378)),
 (538, np.float64(1.324203274295093)),
 (3524, np.float64(1.3234289157626062)),
 (3478, np.float64(1.321347215850287)),

In [16]:
# 过滤掉目标用户已经观看过的电影，不作推荐，比如用户看过1号电影，就把1号电影过滤掉了
filtered_recommended_movies = [(movie_id, score) for movie_id, score in recommendations if movie_id not in watched_items]
filtered_recommended_movies

[(1196, np.float64(58.14925595676199)),
 (1265, np.float64(52.497596689914644)),
 (1198, np.float64(51.414838494877394)),
 (1210, np.float64(47.33033760597222)),
 (2987, np.float64(43.137615048983285)),
 (1197, np.float64(41.044886550557585)),
 (592, np.float64(40.618734013460866)),
 (593, np.float64(40.33598515544499)),
 (318, np.float64(39.827341958323856)),
 (2716, np.float64(39.6878425642731)),
 (356, np.float64(38.28290409649106)),
 (296, np.float64(38.14295004076712)),
 (364, np.float64(37.82143164468238)),
 (1580, np.float64(37.78016136659865)),
 (2081, np.float64(37.6946233462043)),
 (2174, np.float64(37.36975287346132)),
 (1073, np.float64(36.98072733139939)),
 (608, np.float64(36.88914415021277)),
 (1259, np.float64(34.23940992579588)),
 (1307, np.float64(34.21514255734086)),
 (2571, np.float64(33.85356364303985)),
 (1291, np.float64(33.56873042877438)),
 (2858, np.float64(33.35951939052473)),
 (480, np.float64(33.33811232348077)),
 (457, np.float64(32.37111630279746)),
 (1022, np.float64(31.004064227429506)),
 (2396, np.float64(30.217457553287872)),
 (1136, np.float64(29.667385367152583)),
 (1968, np.float64(29.614220955986323)),
 (1282, np.float64(29.1140779064778)),
 (1240, np.float64(28.320006860141465)),
 (2080, np.float64(28.22923914356061)),
 (2096, np.float64(28.071138576631743)),
 (2355, np.float64(27.837542307818424)),
 (1704, np.float64(27.682814683680533)),
 (2078, np.float64(27.474999706567274)),
 (1036, np.float64(27.4371041478716)),
 (2087, np.float64(27.268202879485962)),
 (590, np.float64(27.034578609830646)),
 (2762, np.float64(26.864832688170058)),
 (110, np.float64(26.817773829315577)),
 (1617, np.float64(26.259234958900826)),
 (1394, np.float64(26.14275639355331)),
 (2100, np.float64(25.99227259871263)),
 (1079, np.float64(25.9133682620533)),
 (589, np.float64(25.524685020243936)),
 (1032, np.float64(25.452176875763644)),
 (2640, np.float64(24.672448271929344)),
 (2406, np.float64(24.348697097906992)),
 (1784, np.float64(24.14033770126862)),
 (2000, np.float64(24.109785246447682)),
 (1393, np.float64(23.862644176919524)),
 (2054, np.float64(23.629933901390572)),
 (3471, np.float64(23.41862658524074)),
 (3448, np.float64(23.401900235388396)),
 (50, np.float64(23.260593313756406)),
 (858, np.float64(22.887756708999373)),
 (2291, np.float64(22.273915221427373)),
 (1225, np.float64(22.199400317274304)),
 (1387, np.float64(21.895124664026035)),
 (2085, np.float64(21.702268802952275)),
 (377, np.float64(21.360241367637194)),
 (34, np.float64(21.28751343610604)),
 (1214, np.float64(20.788248589309777)),
 (2628, np.float64(20.667734854924262)),
 (1584, np.float64(20.64744632798155)),
 (2916, np.float64(20.56455158844314)),
 (953, np.float64(20.425960800348346)),
 (596, np.float64(20.297555577390764)),
 (1200, np.float64(19.84149106942617)),
 (3396, np.float64(18.84214944668698)),
 (2137, np.float64(18.758808176324955)),
 (780, np.float64(18.743799746215842)),
 (1610, np.float64(18.61845846506236)),
 (3253, np.float64(18.525143469756504)),
 (2268, np.float64(18.361900421060643)),
 (1025, np.float64(18.12147004052432)),
 (39, np.float64(17.626306124088323)),
 (551, np.float64(17.478432088272907)),
 (3034, np.float64(17.44995732663994)),
 (1682, np.float64(17.290515702043667)),
 (2011, np.float64(17.242459950204534)),
 (1688, np.float64(17.09270862683932)),
 (541, np.float64(16.967911173601383)),
 (1947, np.float64(16.914851464226455)),
 (32, np.float64(16.796549902685797)),
 (2407, np.float64(16.665953473587752)),
 (587, np.float64(16.48004421629626)),
 (2161, np.float64(16.437764038584525)),
 (924, np.float64(16.254336705447923)),
 (2089, np.float64(16.226885537892688)),
 (1380, np.float64(16.207348799532884)),
 (1220, np.float64(16.118337661434882)),
 (2997, np.float64(16.00708693737582)),
 (3418, np.float64(15.592418926156645)),
 (1030, np.float64(15.494833967220991)),
 (2804, np.float64(15.471794595888579)),
 (1033, np.float64(15.105215408080571)),
 (616, np.float64(15.009796862603972)),
 (1923, np.float64(14.99648673037067)),
 (2470, np.float64(14.923861556132149)),
 (2141, np.float64(14.514427367256191)),
 (912, np.float64(14.475213310672144)),
 (2090, np.float64(14.442296988604198)),
 (1221, np.float64(14.304618377666285)),
 (380, np.float64(14.287390545767352)),
 (1674, np.float64(14.119124252870293)),
 (899, np.float64(13.923777795381117)),
 (2194, np.float64(13.721296607378516)),
 (1278, np.float64(13.404650674060766)),
 (1213, np.float64(13.343435304018683)),
 (1517, np.float64(13.302191592873694)),
 (3255, np.float64(13.25825813282328)),
 (1247, np.float64(13.188453207717558)),
 (3361, np.float64(12.83409821534131)),
 (920, np.float64(12.788047287937033)),
 (1090, np.float64(12.757429741518683)),
 (3363, np.float64(12.68726907700513)),
 (3526, np.float64(12.599914260938045)),
 (2915, np.float64(12.538083410531618)),
 (3039, np.float64(12.490075048372463)),
 (3147, np.float64(12.240407900367883)),
 (1954, np.float64(12.214619152827108)),
 (2746, np.float64(12.077158693260959)),
 (1294, np.float64(11.98624167823271)),
 (1302, np.float64(11.868315546687526)),
 (2139, np.float64(11.775186217867901)),
 (2565, np.float64(11.75480861065866)),
 (367, np.float64(11.720569354735499)),
 (508, np.float64(11.441557015331263)),
 (1088, np.float64(11.438270233877326)),
 (2115, np.float64(11.37678211310676)),
 (750, np.float64(11.29775787829264)),
 (1208, np.float64(11.222713138509178)),
 (3421, np.float64(10.934921870695897)),
 (3671, np.float64(10.87751726810024)),
 (1358, np.float64(10.703166123830947)),
 (357, np.float64(10.517949211653605)),
 (2394, np.float64(10.231318641406604)),
 (1304, np.float64(10.19880373156389)),
 (709, np.float64(10.198117143799614)),
 (2005, np.float64(9.896154391573598)),
 (2352, np.float64(9.638595474489568)),
 (2761, np.float64(9.562829007320286)),
 (1641, np.float64(9.552019067005705)),
 (1219, np.float64(9.509218584587636)),
 (3489, np.float64(9.352840381958536)),
 (1222, np.float64(9.266475987025096)),
 (597, np.float64(9.180354440094762)),
 (2857, np.float64(9.145117202777973)),
 (2012, np.float64(9.069944446938536)),
 (3210, np.float64(9.023993474707266)),
 (539, np.float64(8.786549336609552)),
 (1206, np.float64(8.785645641265711)),
 (1500, np.float64(8.715826864185395)),
 (36, np.float64(8.55795954211361)),
 (1271, np.float64(8.514003099493824)),
 (11, np.float64(8.472959282942611)),
 (1242, np.float64(8.440386961161149)),
 (1094, np.float64(8.414220273703048)),
 (904, np.float64(8.325330786966154)),
 (1231, np.float64(8.19397896200115)),
 (440, np.float64(8.112095856225814)),
 (1374, np.float64(8.11005130891401)),
 (2123, np.float64(8.09087336345497)),
 (586, np.float64(8.07759841932354)),
 (1031, np.float64(8.005329901920696)),
 (2144, np.float64(7.988632764892349)),
 (2599, np.float64(7.980141617353448)),
 (2, np.float64(7.920007547122817)),
 (903, np.float64(7.899496466308019)),
 (908, np.float64(7.8441586413615365)),
 (2890, np.float64(7.789074057821588)),
 (1356, np.float64(7.751286368247575)),
 (910, np.float64(7.721718490817631)),
 (3527, np.float64(7.721007716783557)),
 (2739, np.float64(7.655310614555155)),
 (62, np.float64(7.5242806086840375)),
 (1234, np.float64(7.521967982783026)),
 (3751, np.float64(7.507659174381204)),
 (3552, np.float64(7.502528051340928)),
 (3578, np.float64(7.438003891542227)),
 (1013, np.float64(7.436459536701612)),
 (900, np.float64(7.370651065802257)),
 (300, np.float64(7.357832456218698)),
 (1089, np.float64(7.329242610154589)),
 (1951, np.float64(7.320458271728031)),
 (1127, np.float64(7.291026688656567)),
 (2092, np.float64(7.284161743938269)),
 (25, np.float64(7.251891161670367)),
 (1673, np.float64(7.202341549560632)),
 (2302, np.float64(7.156839112956432)),
 (923, np.float64(7.059753772524831)),
 (2529, np.float64(7.0054319453325125)),
 (2657, np.float64(6.962461041204875)),
 (1250, np.float64(6.898911819345539)),
 (1663, np.float64(6.895772924169366)),
 (2324, np.float64(6.7827382801546)),
 (1285, np.float64(6.778144566295451)),
 (3100, np.float64(6.69109199904883)),
 (1527, np.float64(6.4383309289312365)),
 (337, np.float64(6.24071678215876)),
 (3175, np.float64(6.189116812087712)),
 (454, np.float64(6.151863737322828)),
 (2420, np.float64(6.0571322501060925)),
 (1023, np.float64(6.024467095013994)),
 (1376, np.float64(6.0024338693994554)),
 (2985, np.float64(5.999147543368988)),
 (1377, np.float64(5.750275265995701)),
 (1064, np.float64(5.7132426717287395)),
 (2968, np.float64(5.706820502237619)),
 (2395, np.float64(5.7026827696714575)),
 (500, np.float64(5.6908307189888765)),
 (673, np.float64(5.690406815018439)),
 (2048, np.float64(5.590335975488424)),
 (969, np.float64(5.513457677906267)),
 (317, np.float64(5.460171460237577)),
 (1588, np.float64(5.448430567339032)),
 (2099, np.float64(5.408727051548135)),
 (1573, np.float64(5.105623775741659)),
 (111, np.float64(5.079662587148382)),
 (3545, np.float64(5.067449585602741)),
 (3098, np.float64(5.0596083343827525)),
 (3360, np.float64(5.057678110158044)),
 (3608, np.float64(5.0545745959110135)),
 (1276, np.float64(5.035303686115277)),
 (1080, np.float64(5.020065134397413)),
 (3386, np.float64(4.967651104106901)),
 (1084, np.float64(4.958347052607053)),
 (3591, np.float64(4.907039837638959)),
 (1230, np.float64(4.864307141142412)),
 (1288, np.float64(4.831047025997231)),
 (2083, np.float64(4.823186198263437)),
 (1957, np.float64(4.814793799959553)),
 (2371, np.float64(4.764753535151906)),
 (1747, np.float64(4.7421825895408425)),
 (2424, np.float64(4.688771244977001)),
 (2671, np.float64(4.6515219625280535)),
 (648, np.float64(4.595580925502878)),
 (1569, np.float64(4.585813668221495)),
 (1148, np.float64(4.572141056601774)),
 (3252, np.float64(4.374385793330779)),
 (158, np.float64(4.365659810729095)),
 (529, np.float64(4.364506334183325)),
 (362, np.float64(4.335606188986721)),
 (2105, np.float64(4.323856887950497)),
 (2142, np.float64(4.305462739953759)),
 (1293, np.float64(4.27662743056969)),
 (2059, np.float64(4.260651304363828)),
 (736, np.float64(4.254874644318761)),
 (3481, np.float64(4.247437632016193)),
 (1777, np.float64(4.2469219071012345)),
 (3108, np.float64(4.239230906791917)),
 (3675, np.float64(4.235200703198943)),
 (1186, np.float64(4.14750091582669)),
 (2700, np.float64(4.141975864929343)),
 (3549, np.float64(4.126102118576344)),
 (2140, np.float64(4.019367539149524)),
 (2908, np.float64(4.01003627540398)),
 (778, np.float64(4.004930058783605)),
 (3176, np.float64(3.943923903368511)),
 (3398, np.float64(3.9383944200302814)),
 (2020, np.float64(3.903084939395229)),
 (2124, np.float64(3.896935342431461)),
 (1012, np.float64(3.885897433177413)),
 (1639, np.float64(3.800652509306357)),
 (3793, np.float64(3.7780373508624034)),
 (1952, np.float64(3.730986468202709)),
 (1268, np.float64(3.7115947302936974)),
 (1081, np.float64(3.7038546682079705)),
 (2959, np.float64(3.672712365885931)),
 (1120, np.float64(3.670823230559705)),
 (2067, np.float64(3.667194740359207)),
 (1258, np.float64(3.6120371561599436)),
 (239, np.float64(3.5536444261196474)),
 (2871, np.float64(3.511774478081236)),
 (153, np.float64(3.4940157472391817)),
 (2193, np.float64(3.488455062290618)),
 (1252, np.float64(3.4561138184125095)),
 (3702, np.float64(3.436797339200268)),
 (1702, np.float64(3.390733964536909)),
 (1370, np.float64(3.3358969613494205)),
 (1228, np.float64(3.3258654458242103)),
 (3087, np.float64(3.3203339893732577)),
 (2003, np.float64(3.2854830953775176)),
 (2366, np.float64(3.2769451941893366)),
 (21, np.float64(3.275893642816736)),
 (2354, np.float64(3.265393116872969)),
 (1920, np.float64(3.255726612714673)),
 (2001, np.float64(3.251390490744406)),
 (1204, np.float64(3.2370227236476325)),
 (3504, np.float64(3.2350984442803203)),
 (1183, np.float64(3.1819418177930543)),
 (1678, np.float64(3.1612351473277425)),
 (2082, np.float64(3.135549262097662)),
 (1124, np.float64(3.117182386889551)),
 (2728, np.float64(3.109785604900563)),
 (2398, np.float64(3.0945210900680467)),
 (1021, np.float64(3.0740497946093566)),
 (1223, np.float64(3.050351902588833)),
 (1024, np.float64(2.9426879645436137)),
 (316, np.float64(2.934248516354411)),
 (1017, np.float64(2.85554041940906)),
 (832, np.float64(2.8457620587189583)),
 (2145, np.float64(2.8279674038750144)),
 (2474, np.float64(2.803272132964941)),
 (3071, np.float64(2.7875927609118336)),
 (47, np.float64(2.7764019421951853)),
 (3897, np.float64(2.6564851968930645)),
 (3160, np.float64(2.627863195515464)),
 (1103, np.float64(2.627740125319506)),
 (235, np.float64(2.6094933730241734)),
 (2941, np.float64(2.590688011869964)),
 (3148, np.float64(2.59034147949711)),
 (223, np.float64(2.5881584156340804)),
 (1266, np.float64(2.551398448780946)),
 (515, np.float64(2.5256950117359955)),
 (2683, np.float64(2.521394084676974)),
 (3317, np.float64(2.5014645648997567)),
 (901, np.float64(2.4820991199713687)),
 (2863, np.float64(2.425117058742728)),
 (2712, np.float64(2.358539842797998)),
 (2243, np.float64(2.2938173607717234)),
 (1416, np.float64(2.2932999669718486)),
 (902, np.float64(2.2733149927540115)),
 (1060, np.float64(2.246402168996273)),
 (3061, np.float64(2.238072963842699)),
 (3072, np.float64(2.208259739416059)),
 (455, np.float64(2.1911941955472005)),
 (339, np.float64(2.1857666215271685)),
 (733, np.float64(2.18114251973025)),
 (3429, np.float64(2.176382687753631)),
 (2971, np.float64(2.168013539090131)),
 (2336, np.float64(2.1586253948278875)),
 (107, np.float64(2.1393490727796713)),
 (3052, np.float64(2.1370790428922604)),
 (372, np.float64(2.1245139981736454)),
 (3256, np.float64(2.1037475264924597)),
 (474, np.float64(2.0911626495421896)),
 (945, np.float64(2.0881083079379055)),
 (441, np.float64(2.0823514878582254)),
 (313, np.float64(2.0679736906261654)),
 (3301, np.float64(2.051015173434313)),
 (2353, np.float64(2.043546504194618)),
 (2947, np.float64(2.041010256609431)),
 (2724, np.float64(2.0351363360315493)),
 (1263, np.float64(2.030020318549891)),
 (6, np.float64(2.0195931466492936)),
 (349, np.float64(2.003348044113526)),
 (2427, np.float64(1.9984332849509556)),
 (17, np.float64(1.9939208118845921)),
 (1635, np.float64(1.9878035105904353)),
 (1953, np.float64(1.9813275076357768)),
 (2944, np.float64(1.980021744254369)),
 (3362, np.float64(1.9792594058903838)),
 (916, np.float64(1.9739361616515083)),
 (915, np.float64(1.940137827726201)),
 (2108, np.float64(1.9382169906008124)),
 (1262, np.float64(1.938063293519131)),
 (45, np.float64(1.920465403147856)),
 (161, np.float64(1.9157492870100425)),
 (911, np.float64(1.9083659017301624)),
 (1614, np.float64(1.904816832008056)),
 (1967, np.float64(1.8982547012637712)),
 (898, np.float64(1.8846074930007761)),
 (2912, np.float64(1.8749697230162972)),
 (2949, np.float64(1.8709166590329613)),
 (1729, np.float64(1.8628518039487734)),
 (2501, np.float64(1.8312644362550814)),
 (2289, np.float64(1.826686794163911)),
 (940, np.float64(1.8236848063499989)),
 (1608, np.float64(1.813964306472343)),
 (1201, np.float64(1.8084945495025309)),
 (2948, np.float64(1.8083400928986537)),
 (1272, np.float64(1.8031953272037433)),
 (928, np.float64(1.7879821224018375)),
 (933, np.float64(1.7791628144584712)),
 (3668, np.float64(1.7776970369654292)),
 (2248, np.float64(1.770299278959491)),
 (16, np.float64(1.7684920000515114)),
 (1283, np.float64(1.7682523821728315)),
 (2792, np.float64(1.7673020299530469)),
 (3654, np.float64(1.7464916033738385)),
 (2590, np.float64(1.744392584235173)),
 (1257, np.float64(1.7301637030837045)),
 (2006, np.float64(1.723931989287165)),
 (3703, np.float64(1.7217348470918747)),
 (3244, np.float64(1.7130245516994471)),
 (3451, np.float64(1.7081175332270677)),
 (1365, np.float64(1.7053713054123096)),
 (1041, np.float64(1.7018400683958779)),
 (2991, np.float64(1.6980301458443878)),
 (3868, np.float64(1.6843232232468175)),
 (2019, np.float64(1.6802390098405922)),
 (2795, np.float64(1.662792137972772)),
 (2455, np.float64(1.6593081417483437)),
 (2134, np.float64(1.6528091412537778)),
 (1297, np.float64(1.646770529805345)),
 (501, np.float64(1.6465151461330985)),
 (2951, np.float64(1.6461293272081283)),
 (2160, np.float64(1.6421952102357384)),
 (2125, np.float64(1.6403602493713563)),
 (3260, np.float64(1.6324457572443742)),
 (3168, np.float64(1.6148375521993774)),
 (3035, np.float64(1.6095508173873365)),
 (2150, np.float64(1.6086377508940002)),
 (253, np.float64(1.6007683631261513)),
 (3062, np.float64(1.581679572038642)),
 (2993, np.float64(1.580422274882839)),
 (1233, np.float64(1.5702636874670528)),
 (1275, np.float64(1.565529418503437)),
 (1254, np.float64(1.5644277890686784)),
 (1019, np.float64(1.556593227681913)),
 (2872, np.float64(1.5542795868409685)),
 (1253, np.float64(1.5534875690528551)),
 (148, np.float64(1.5471170690777336)),
 (1199, np.float64(1.5449627582581993)),
 (1810, np.float64(1.5423973880955757)),
 (369, np.float64(1.541223320280677)),
 (2088, np.float64(1.5369032446333066)),
 (1958, np.float64(1.5312521093609386)),
 (1061, np.float64(1.5215252890174997)),
 (3107, np.float64(1.5193517072395026)),
 (57, np.float64(1.5193125323851446)),
 (1096, np.float64(1.5185149899476842)),
 (3499, np.float64(1.5177313659242246)),
 (1357, np.float64(1.512151883217886)),
 (2611, np.float64(1.5068843710887316)),
 (3623, np.float64(1.5060876390225064)),
 (1274, np.float64(1.506065658392809)),
 (1625, np.float64(1.5031298597858394)),
 (2312, np.float64(1.495354180680176)),
 (1950, np.float64(1.4838606107212005)),
 (1956, np.float64(1.4790780342749046)),
 (2313, np.float64(1.478618418795537)),
 (3095, np.float64(1.4749310003449072)),
 (3468, np.float64(1.4725914125785284)),
 (1185, np.float64(1.4717090002590472)),
 (1945, np.float64(1.4675391904017843)),
 (1104, np.float64(1.4614780319225122)),
 (2580, np.float64(1.4572315296714258)),
 (1955, np.float64(1.4539335520183794)),
 (1912, np.float64(1.438602987039718)),
 (1203, np.float64(1.4305395135033017)),
 (1267, np.float64(1.4123736018743336)),
 (3753, np.float64(1.4070880049148284)),
 (1101, np.float64(1.4065603758247889)),
 (954, np.float64(1.3873423987388693)),
 (2245, np.float64(1.3767313549966909)),
 (3510, np.float64(1.368189624109278)),
 (1701, np.float64(1.364630075811635)),
 (918, np.float64(1.3610955540109888)),
 (125, np.float64(1.3392698382621473)),
 (3359, np.float64(1.3387428216877897)),
 (3298, np.float64(1.338569311895993)),
 (3684, np.float64(1.3333136937696004)),
 (2429, np.float64(1.3243372938430378)),
 (538, np.float64(1.324203274295093)),
 (3524, np.float64(1.3234289157626062)),
 (3478, np.float64(1.321347215850287)),
 (3111, np.float64(1.317953814225978)),
 (3068, np.float64(1.3154677059074655)),
 (2542, np.float64(1.314487418513025)),
 (3469, np.float64(1.3141721462661486)),
 (3152, np.float64(1.2962251417154325)),
 (926, np.float64(1.2933561583575248)),
 (3534, np.float64(1.290347741069807)),
 (3604, np.float64(1.2889896921194035)),
 (1299, np.float64(1.2883032628684512)),
 (1921, np.float64(1.2828360581684102)),
 (922, np.float64(1.2812347281498073)),
 (2300, np.float64(1.2806542271439787)),
 (1135, np.float64(1.2764195918965973)),
 (1732, np.float64(1.2730387337530762)),
 (293, np.float64(1.2713699540115553)),
 (3247, np.float64(1.267913954671599)),
 (262, np.float64(1.2671311271485708)),
 (2953, np.float64(1.2656809558860882)),
 (3755, np.float64(1.2639399514429397)),
 (1748, np.float64(1.255442195530513)),
 (94, np.float64(1.2524597806188977)),
 (1015, np.float64(1.2502955741401367)),
 (562, np.float64(1.2489480009475964)),
 (866, np.float64(1.248683328301596)),
 (2706, np.float64(1.2485736965329417)),
 (1396, np.float64(1.2451314493475591)),
 (2391, np.float64(1.2446841382873814)),
 (558, np.float64(1.244677673089458)),
 (2502, np.float64(1.2412421773274955)),
 (3798, np.float64(1.2330748903339135)),
 (1966, np.float64(1.2302222002460854)),
 (3948, np.float64(1.2300200840961977)),
 (2763, np.float64(1.224338703943401)),
 (3555, np.float64(1.2168391517210868)),
 (3893, np.float64(1.2158862370589758)),
 (1485, np.float64(1.206047531636032)),
 (2881, np.float64(1.1877181664206318)),

In [17]:
# 裁减前10的作品
filtered_recommended_movies = filtered_recommended_movies[:10]
filtered_recommended_movies

[(1196, np.float64(58.14925595676199)),
 (1265, np.float64(52.497596689914644)),
 (1198, np.float64(51.414838494877394)),
 (1210, np.float64(47.33033760597222)),
 (2987, np.float64(43.137615048983285)),
 (1197, np.float64(41.044886550557585)),
 (592, np.float64(40.618734013460866)),
 (593, np.float64(40.33598515544499)),
 (318, np.float64(39.827341958323856)),
 (2716, np.float64(39.6878425642731))]

In [18]:
# 把ID筛选出来
recommended_result = [movie_id for movie_id, _ in filtered_recommended_movies]
recommended_result

[1196, 1265, 1198, 1210, 2987, 1197, 592, 593, 318, 2716]

In [19]:
# 用户1在测试集里评价过的电影（在这个实验中因为被划为测试集，所以当成是他没看过，但喜欢的电影）
test_data_user_liked = ratings_df_test[ratings_df_test['user_id'] == user_id]
real_result = test_data_user_liked["movie_id"]
real_result

12    2398
4     2355
37    1022
38    2762
51     608
5     1197
7     2804
Name: movie_id, dtype: int64

In [20]:
# 取交集用于算指标，即推荐中用户喜欢的百分比
intersection_result = list(set(real_result) & set(recommended_result))
intersection_result

[1197]

In [21]:
# 算出精确度
precision = len(intersection_result) / len(recommended_result)
precision

0.1

### 将代码打包成函数，并使用函数测试

In [22]:
# 为了评测代码，将获取推荐的过程写成函数（用户的相似度矩阵不用再浪费时间计算）
# 函数输入用户ID，相似度矩阵，用户-物品矩阵，要找多少个相似的人做统计，推荐前多少部电影，输出为推荐的电影

def get_user_recommendations(target_user, item_similairty_df, user_item_matrix, similar_item_K, N):

    # 获取该用户看过的电影
    watched_items = user_item_matrix.loc[user_id][user_item_matrix.loc[user_id].astype(bool)].index

    # 针对每一个电影，通过“物品 -> 物品”的索引，找到top-k相似物品，这里的成品只能是一个字典，没法做成一个二维表
    top_k_similar_items_dict = {}

    for item in watched_items:
        if item in item_similarity_df.index:
            similar_items = item_similarity_df.loc[item].sort_values(ascending=False)[1:similar_movies_num_k+1]
            top_k_similar_items_dict[item] = similar_items

    movie_scores = {}

    # 计算每个用户看过电影的总相似度
    for movie, similar_items in top_k_similar_items_dict.items():
        for similar_movie, similarity_score in similar_items.items():
            if similar_movie not in movie_scores:
                movie_scores[similar_movie] = 0
            movie_scores[similar_movie] = movie_scores[similar_movie] + similarity_score * user_item_matrix.loc[target_user,movie]  

    # 对推荐电影按照总相似度进行排序
    recommendations = sorted(movie_scores.items(), key=lambda x: x[1], reverse=True)

    # 过滤用户看过的电影
    filtered_recommended_movies = [(movie_id, score) for movie_id, score in recommendations if movie_id not in watched_items]

    filtered_recommended_movies = filtered_recommended_movies[:10]
    recommended_result = [movie_id for movie_id, _ in filtered_recommended_movies]


    # 取统计分的前N个作推荐
    return recommended_result

In [23]:
user_51_ratings = user_item_matrix.loc[51,1337]
user_51_ratings

np.float64(4.0)

In [24]:
# 测试get_user_recommendations函数是否可以使用
recommendations = get_user_recommendations(51, item_similarity_df, user_item_matrix, 80, 10)
recommendations

[364, 1265, 1580, 1196, 2571, 2355, 1210, 480, 1198, 377]

### 对1~6040用户都进行推荐，并使用测试集的数据来验证

In [25]:
# 注意：按照书中的算法，在云环境中跑了300~400秒，还是可以接受的时间

all_recommendations_num = 0
precise_recommendations_num = 0

similar_movies_num_K = 10
recommend_num = 5

for user_id in set(ratings_df_test["user_id"]):

    # 在测试集中找到用户曾今看过的电影，用于作评估
    test_data_user_liked = ratings_df_test[ratings_df_test['user_id'] == user_id]
    real_result = test_data_user_liked["movie_id"]

    recommendations = get_user_recommendations(user_id, item_similarity_df, user_item_matrix, similar_movies_num_K, recommend_num)

    # 推荐的物品是用户喜欢的，intersection：交集
    intersection_result = list(set(real_result) & set(recommendations))
    
    # 统计精确推荐（推荐的刚好是用户喜欢的） 做分子 这个变量就是混淆矩阵中的TP
    precise_recommendations_num += len(intersection_result)

    # 统计推荐总数 做分母 是TP + FP
    all_recommendations_num += len(recommendations)

# 求出精确度
precision = precise_recommendations_num / all_recommendations_num

In [26]:
print(precision)

0.20652317880794702

In [27]:
len(ratings_df_test)

125027

In [28]:
# 求出混淆矩阵中的各个指标，用于后续验证
TP = precise_recommendations_num
FP = all_recommendations_num - TP

# FN：预测错了的负样本，可以通过测试集的长度 - TP得到（详情可以查看PPT中的混淆矩阵部分）
FN =  len(ratings_df_test) - TP

print("TP: " + str(TP))
print("FP: " + str(FP))
print("FN: " + str(FN))

TP: 12474
FP: 47926
FN: 112553

In [29]:
precision = TP / (TP+FP)
recall = TP/ (TP+FN)

f1_score = 2 * (precision * recall) / (precision + recall)

In [30]:
print("推荐的物品中用户喜欢的数量：" + str(precise_recommendations_num))
print("推荐的物品总数：" + str(all_recommendations_num))
print("精确度：" + str(precision))
print("召回率：" + str(recall))
print("F1-score：" + str(f1_score))

推荐的物品中用户喜欢的数量：12474
推荐的物品总数：60400
精确度：0.20652317880794702
召回率：0.0997704495828901
F1-score：0.13454351308061932